// Generated by CoffeeScript 1.9.1
(function() {
  var BasicObject, Cross, TweenMax,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BasicObject = require('./BasicObject');

  TweenMax = require('gsap');

  Cross = (function(superClass) {
    extend(Cross, superClass);

    function Cross() {
      this.animate = bind(this.animate, this);
      return Cross.__super__.constructor.apply(this, arguments);
    }

    Cross.prototype.animate = function(out) {
      var a;
      if (out == null) {
        out = false;
      }
      Cross.__super__.animate.call(this, out);
      a = {
        w: this.size[0] / 4 - this.lineWidth / 2,
        h: this.size[1] / 2 - this.lineWidth / 2
      };
      this.ctx.moveTo(this.size[0] / 4 - this.lineWidth / 2, this.size[1] / 2 - this.lineWidth / 2);
      if (out) {
        this.ctx.lineWidth = 17;
      }
      TweenMax.to(a, .3, {
        h: (this.size[1] / 2 + this.size[1] / 4) - this.lineWidth / 2,
        w: (this.size[0] / 2 + this.size[0] / 4) - this.lineWidth / 2,
        ease: (out ? "easeOutQuart" : "easeInExpo"),
        delay: 1 - parseInt(out),
        onUpdate: (function(_this) {
          return function() {
            _this.ctx.moveTo(_this.size[0] / 4 - _this.lineWidth / 2, _this.size[1] / 2 - _this.lineWidth / 2);
            _this.ctx.lineTo(a.w, _this.size[1] / 2 - _this.lineWidth / 2);
            _this.ctx.stroke();
            _this.ctx.moveTo(_this.size[0] / 2 - _this.lineWidth / 2, _this.size[1] / 4 - _this.lineWidth / 2);
            _this.ctx.lineTo(_this.size[0] / 2 - _this.lineWidth / 2, a.h);
            return _this.ctx.stroke();
          };
        })(this),
        onComplete: (function(_this) {
          return function() {
            if (!out) {
              return setTimeout(_this.animate, 2000, true);
            } else {
              return _this.resetShowAnim();
            }
          };
        })(this)
      });
      return null;
    };

    return Cross;

  })(BasicObject);

  module.exports = Cross;

}).call(this);
