// Generated by CoffeeScript 1.9.1
(function() {
  var Config;

  Config = (function() {
    function Config() {}

    Config.COLOURS = {
      red: 'rgba(235, 35, 40,1)',
      yellow: 'rgba(255, 255, 40,1)',
      blue: 'rgba(100, 200, 230,1)',
      green: 'rgba(95, 185, 80,1)',
      pink: 'rgba(250, 200, 220,1)',
      black: 'rgba(0,0,0,1)',
      purple: 'rgba(100, 45, 140,1)'
    };

    Config.GRADIENTS = [[Config.COLOURS.red, Config.COLOURS.yellow], [Config.COLOURS.pink, Config.COLOURS.black], [Config.COLOURS.green, Config.COLOURS.blue], [Config.COLOURS.purple, Config.COLOURS.blue], [Config.COLOURS.pink, Config.COLOURS.purple], [Config.COLOURS.yellow, Config.COLOURS.green], [Config.COLOURS.red, Config.COLOURS.pink]];

    return Config;

  })();

  module.exports = Config;

}).call(this);
