// Generated by CoffeeScript 1.9.1
(function() {
  var Rect2;

  Rect2 = (function() {
    function Rect2(x, y, width, height) {
      this.x = x != null ? x : 0;
      this.y = y != null ? y : 0;
      this.width = width != null ? width : 0;
      this.height = height != null ? height : 0;
    }

    Rect2.prototype.hitTest = function(r) {
      return (r.x + r.width >= this.x) && (r.x <= this.x + this.width) && (r.y + r.height >= this.y) && (r.y <= this.y + this.height);
    };

    return Rect2;

  })();

  module.exports = Rect2;

}).call(this);
